export const turkishTranslations = {
    "smartphones": "Akıllı Telefon",
    "laptops": "Laptop",
    "fragrances": "Parfüm",
    "skincare": "Cilt Bakımı",
    "groceries": "Market Alışverişi",
    "home-decoration": "Ev Dekorasyonu",
    "furniture": "Mobilya",
    "tops": "Üst Giyim",
    "womens-dresses": "Kadın Elbiseleri",
    "womens-shoes": "Kadın Ayakkabıları",
    "mens-shirts": "Erkek Gömlekleri",
    "mens-shoes": "Erkek Ayakkabıları",
    "mens-watches": "Erkek Saatleri",
    "womens-watches": "Kadın Saatleri",
    "womens-bags": "Kadın Çantaları",
    "womens-jewellery": "Kadın Takıları",
    "sunglasses": "Güneş Gözlüğü",
    "automotive": "Otomotiv",
    "motorcycle": "Motosiklet",
    "lighting": "Aydınlatma"
};
